# FROM almalinux:9
# RUN dnf install nginx -y
# LABEL course="Docker"\
#       duration="100hrs"\
#       student="Siva"
# EXPOSE 80
# ENV subject="Devops"\
#     Class="Btech"
# CMD [ "nginx","-g","daemon off;" ] 

FROM almalinux:9
ENTRYPOINT [ "ping","-c5" ]
CMD [  "google.com"] 


