# Play level variables
- name: ansible paly level variables
  hosts: localhost
  become: true
  vars:
    COURSE: DevOps
    DURATION: 3 Months
    STUDENT: Shivakumar
  tasks:
  - name: play level variables
    ansible.builtin.debug:
      msg: Hi im Siva good morning

  - name: play level variables
    ansible.builtin.debug:
      msg: Hi im a {{ STUDENT }} learning {{ COURSE }} and duration is {{ DURATION }}

# Task level variables

- name: ansible paly level variables
  hosts: localhost
  become: true
  tasks:
  - name: play level variables
    vars:
      TV: Samsung
      COST: 20000
    ansible.builtin.debug:
      msg: Hi im Siva good morning

  - name: play level variables
    ansible.builtin.debug:
      msg: Hi im a purchase a {{ TV }}, cost of tv was {{ COST }}