# Play level variables
- name: ansible paly level variables
  hosts: localhost
  become: true
  vars:
    COURSE: DevOps
    DURATION: 3 Months
    STUDENT: Shivakumar
  tasks:
  - name: play level variables
    ansible.builtin.debug:
      msg: Hi im Siva good morning

  - name: play level variables
    ansible.builtin.debug:
      msg: Hi im a {{ STUDENT }} learning {{ COURSE }} and duration is {{ DURATION }}

# Task level variables

- name: ansible task level variables
  hosts: localhost
  become: true
  tasks:
  - name: task level variables
    ansible.builtin.debug:
      msg: Hi im Siva good morning

  - name: task level variables
    vars:
      TV: Samsung
      COST: 20000
    ansible.builtin.debug:
      msg: Hi im a purchase a {{ TV }}, cost of tv was {{ COST }}

# variables from variables file

- name: ansible variables from vars file
  hosts: localhost
  become: true
  vars_files:
  - variables.yaml
  tasks:
  - name: variables from vars file
    ansible.builtin.debug:
      msg: Hi im Siva good morning

  - name: variables from vars file
    ansible.builtin.debug:
      msg: Hi studying {{CLASS}}, from {{VILLAGE}}, at {{SCHOOL}}

# variables from prompt

- name: ansible variables from prompt
  hosts: localhost
  become: true
  vars_prompt:
  - name: USERNAME
    prompt: please enter username
    private: false
  - name: PASSWORD
    prompt: please enter password 
    private: true
  tasks:
  - name: variables from prompt
    ansible.builtin.debug:
      msg: Hi im Siva good morning

  - name: variables from prompt
    ansible.builtin.debug:
      msg: username is  {{ USERNAME }} and password is {{ PASSWORD }}

# variables from inventory file

- name: Inventory level variables
  hosts: web
  become: true
  tasks:
  - name: inventory level vars
    ansible.builtin.debug:
      msg: Hi good morning im Siva

  - name: inventorylevel vars
    ansible.builtin.debug:
      msg: Hi working in {{ COMPANY }},i have {{ EXPERIENCE }} of experience.