---
- name: install apache2
  hosts: all
  become: true
  tasks:
    - name: install apache2 service
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: copy index.html file
      ansible.builtin.copy:
        src: index.html
        dest: /var/index.html
        owner: root
        group: root
        mode: '0644'
        