- name: Install nginx server nad start the service
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.apt:
      name: nginx
      state: latest
  - name: start the service
    ansible.builtin.service:
      name: naginx
      state: started