- name: db configuration
  hosts: db
  become: true
  vars:
  - name: mysql_root_password
    prompt: please enter password
    private: no
  tasks:
  - name: install mysql server
    ansible.builtin.dnf:
      name: mysql-server
      state: latest

  - name: enable the service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: install python Packages
    ansible.builtin.pip:
      name:
      - pymysql
      - cryptography
      executable: pip3.9

  - name: check db connection
    community.mysql.mysql_db:
      login_user: root
      login_password: "{{mysql_root_password}}"
      login_host: db.sdevops.cloud 
    ignore_errors: yes
    register: mysql_connection_output

  - name: print the output of db connection
    ansible.builtin.debug:
      msg: "{{mysql_connection_output}}"

  - name: set password
    ansible.builtin.command: mysql_secure_installation --set-root-pass {{mysql_root_password}}
    when: mysql_connection_output.failed is true



    
